data:
  image: busybox
  volumes:
    - $KALABOX_APP_ROOT_BIND/files:/media:rw
    - /certs
    - /sql
    - /code
appserver:
  image: drupal
  links:
    - db:db
  ports:
    - "80"
db:
  image: mysql
  volumes_from:
    - data
  volumes:
    - /sql:/var/lib/mysql
  environment:
    MYSQL_USER: eight
    MYSQL_PASSWORD: eight
    MYSQL_ROOT_PASSWORD: eight
    MYSQL_DATABASE: eight
