data:
  image: busybox
  volumes:
    - $KALABOX_APP_ROOT_BIND/files:/media:rw
    - /var/lib/mysql
    - /var/www/html
appserver:
  image: drupal:8
  volumes_from:
    - data
  links:
    - db:db
  ports:
    - "80"
db:
  image: mysql
  volumes_from:
    - data
  environment:
    MYSQL_USER: eight
    MYSQL_PASSWORD: eight
    MYSQL_ROOT_PASSWORD: eight
    MYSQL_DATABASE: eight
